# ----
# Site

title: Crown Chronicles
url:
baseurl:
google_analytics_key:
google_maps_javascript_api_key:
disqus_shortname:

timezone: Etc/UTC

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE