# ----
# Site

title: Crown Chronicles
url: https://hytaleserverproject.github.io
baseurl: /crownchronicles/
google_analytics_key:
google_maps_javascript_api_key:
disqus_shortname:

timezone: Etc/UTC

exclude: [vendor]
